services:
  app:
    image: ${DOCKERHUB_IMAGE}:${IMAGE_TAG}
    container_name: travlocks-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      TZ: Asia/Seoul

      # Spring profile
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}

      # RDS
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      # Redis
      SPRING_DATA_REDIS_HOST: ${SPRING_DATA_REDIS_HOST}
      SPRING_DATA_REDIS_PORT: ${SPRING_DATA_REDIS_PORT}

      # S3
      AWS_REGION: ${AWS_REGION}
      AWS_S3_BUCKET: ${AWS_S3_BUCKET}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
